    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Create Prom User
      ansible.builtin.user:
        name: docker
        group: docker
        shell: /sbin/nologin
    
    
    - name: Install docker
      ansible.builtin.yum:
        name: docker
        state: present
        update_cache: true

    - name: Ensure docker is started and enabled
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

