    - name: Download Long Term Jenkins release
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import jenkins key from url
      ansible.builtin.apt_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: yum update
      ansible.builtin.apt:
        name: '*'
        state: latest

    - name: Install java
      ansible.builtin.apt:
        name: java-11-openjdk-devel
        state: present

    - name: Install jenkins
      ansible.builtin.apt:
        name: jenkins
        state: latest

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started