services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8100:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - net
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
networks:
  net: